# This rule is not used by the project cert-renewer-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cert.compute.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cert-renewer-operator
    app.kubernetes.io/managed-by: kustomize
  name: issuerconfig-viewer-role
rules:
- apiGroups:
  - cert.compute.io
  resources:
  - issuerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert.compute.io
  resources:
  - issuerconfigs/status
  verbs:
  - get
