---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert.compute.io
  resources:
  - issuerconfigs
  - ocpcertificatetrackers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert.compute.io
  resources:
  - issuerconfigs/finalizers
  - ocpcertificatetrackers/finalizers
  verbs:
  - update
- apiGroups:
  - cert.compute.io
  resources:
  - issuerconfigs/status
  - ocpcertificatetrackers/status
  verbs:
  - get
  - patch
  - update
