apiVersion: v1
kind: ConfigMap
metadata:
  name: pebble-config
  namespace: ocp-controller-cert-renewer
data:
  pebble-config.json: |
    {
      "pebble": {
        "listenAddress": ":14000",
        "managementListenAddress": ":15000",
        "externalAccountBindingRequired": false,
        "certificate": "/test/certs/tls.crt",
        "privateKey": "/test/certs/tls.key"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pebble
  namespace: ocp-controller-cert-renewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pebble
  template:
    metadata:
      labels:
        app: pebble
    spec:
      containers:
        - name: pebble
          image: letsencrypt/pebble
          command: ["pebble", "-config", "/test/config/pebble-config.json"]
          ports:
            - containerPort: 14000 
          env:
            - name: PEBBLE_VA_NOSLEEP
              value: "1"
          volumeMounts:
            - name: pebble-config
              mountPath: /test/config
              readOnly: true
            - name: pebble-tls
              mountPath: /test/certs
              readOnly: true
      volumes:
        - name: pebble-config
          configMap:
            name: pebble-config
        - name: pebble-tls
          secret:
            secretName: pebble-tls
---
apiVersion: v1
kind: Service
metadata:
  name: pebble
  namespace: ocp-controller-cert-renewer
spec:
  selector:
    app: pebble
  ports:
    - name: acme
      port: 14000
      targetPort: 14000