apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage
spec:
  storageClassDevices:
  - storageClassName: localblock
    volumeMode: Block
    devicePaths:
    - /dev/sda3
    - /dev/sda4
    
